### ISSUE TITLE
Rails Fixtures don't run callbacks

### ISSUE THREAD

**Issue by mattes** [mattes/ksuid-ruby#4]
Rails Fixtures don't run callbacks, i.e. [`after_initialize`](https://github.com/mattes/ksuid-ruby/blob/8c748cf3e6a567519faa4ae5790ba85387f48ed1/lib/ksuid/activerecord.rb#L13). 

Work-around: initialize with KSUID.new or static KSUID.

```
# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

# This model initially had no columns defined. If you add columns to the
# model remove the '{}' from the fixture names and add the columns immediately
# below each fixture, per the syntax in the comments below
#
user:
  id: <%= KSUID.new %>
  email: mike@example.com
```
